### ISSUE TITLE
Attachment filenames in send_email not really formatted

### ISSUE THREAD

**Issue by Etoneja** [olegborzov/helloworld_back#1]
https://github.com/olegborzov/helloworld_back/blob/72144215efc9e9627cd6a1f5daeb357c384da2eb/app_celery/utils/email.py#L34

https://github.com/olegborzov/helloworld_back/blob/72144215efc9e9627cd6a1f5daeb357c384da2eb/app_celery/utils/email.py#L37

Looks like missed curly brackets. Didn't test it in the running project.

**Comment by olegborzov** [comment]
@Etoneja thank you for reply, fixed it)
